### ISSUE TITLE
FFmpeg Source Code

### ISSUE THREAD

**Issue by kierank** [awslabs/aws-fpga-app-notes#11]
Hello,

It seems that you are hosting an FFmpeg binary with some modifications.
As a copyright holder of FFmpeg please can you provide full, unmodified source code.

Kieran

**Comment by hyandell** [comment]
Thanks Kieran. Looking into this.

**Comment by kierank** [comment]
Added to FFmpeg trac: https://trac.ffmpeg.org/ticket/7214

**Comment by hyandell** [comment]
Thanks again Kieran :) I'll make sure to provide updates both here and on FFmpeg's trac.

**Comment by hyandell** [comment]
I've updated on the ffmpeg Trac. Thank you again for raising this Kieran.

Resolving here.

**Comment by hyandell** [comment]
Also wanted to thank @dwbuiten for his note on twitter and the review (we'd noticed the same issue of an empty commit; sorry for not seeing your comment).
